// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example_service.proto

package biz.neustar.ultra.service.example;

public final class ExampleServiceMessage {
  private ExampleServiceMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025example_service.proto\022\017service.example" +
      "\032\025example_request.proto\032\026example_respons" +
      "e.proto2c\n\016ExampleService\022Q\n\014getSomethin" +
      "g\022\037.service.example.ExampleRequest\032 .ser" +
      "vice.example.ExampleResponseB@\n!biz.neus" +
      "tar.ultra.service.exampleB\025ExampleServic" +
      "eMessage\200\001\000\210\001\000"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          biz.neustar.ultra.service.example.ExampleRequestMessage.getDescriptor(),
          biz.neustar.ultra.service.example.ExampleResponseMessage.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
