// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example_request.proto

package biz.neustar.ultra.service.example;

public final class ExampleRequestMessage {
  private ExampleRequestMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface NestedItemOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string value = 1;
    boolean hasValue();
    String getValue();
  }
  public static final class NestedItem extends
      com.google.protobuf.GeneratedMessage
      implements NestedItemOrBuilder {
    // Use NestedItem.newBuilder() to construct.
    private NestedItem(Builder builder) {
      super(builder);
    }
    private NestedItem(boolean noInit) {}
    
    private static final NestedItem defaultInstance;
    public static NestedItem getDefaultInstance() {
      return defaultInstance;
    }
    
    public NestedItem getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return biz.neustar.ultra.service.example.ExampleRequestMessage.internal_static_service_example_NestedItem_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return biz.neustar.ultra.service.example.ExampleRequestMessage.internal_static_service_example_NestedItem_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string value = 1;
    public static final int VALUE_FIELD_NUMBER = 1;
    private Object value_;
    public boolean hasValue() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getValue() {
      Object ref = value_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          value_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getValueBytes() {
      Object ref = value_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      value_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getValueBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getValueBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItem prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return biz.neustar.ultra.service.example.ExampleRequestMessage.internal_static_service_example_NestedItem_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return biz.neustar.ultra.service.example.ExampleRequestMessage.internal_static_service_example_NestedItem_fieldAccessorTable;
      }
      
      // Construct using biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItem.getDescriptor();
      }
      
      public biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItem getDefaultInstanceForType() {
        return biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItem.getDefaultInstance();
      }
      
      public biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItem build() {
        biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItem buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItem buildPartial() {
        biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItem result = new biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItem(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItem) {
          return mergeFrom((biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItem other) {
        if (other == biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItem.getDefaultInstance()) return this;
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              value_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string value = 1;
      private Object value_ = "";
      public boolean hasValue() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getValue() {
        Object ref = value_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setValue(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        value_ = value;
        onChanged();
        return this;
      }
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      void setValue(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        value_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:service.example.NestedItem)
    }
    
    static {
      defaultInstance = new NestedItem(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:service.example.NestedItem)
  }
  
  public interface ExampleRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string something = 1;
    boolean hasSomething();
    String getSomething();
    
    // optional .service.example.NestedItem item = 2;
    boolean hasItem();
    biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItem getItem();
    biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItemOrBuilder getItemOrBuilder();
  }
  public static final class ExampleRequest extends
      com.google.protobuf.GeneratedMessage
      implements ExampleRequestOrBuilder {
    // Use ExampleRequest.newBuilder() to construct.
    private ExampleRequest(Builder builder) {
      super(builder);
    }
    private ExampleRequest(boolean noInit) {}
    
    private static final ExampleRequest defaultInstance;
    public static ExampleRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public ExampleRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return biz.neustar.ultra.service.example.ExampleRequestMessage.internal_static_service_example_ExampleRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return biz.neustar.ultra.service.example.ExampleRequestMessage.internal_static_service_example_ExampleRequest_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string something = 1;
    public static final int SOMETHING_FIELD_NUMBER = 1;
    private Object something_;
    public boolean hasSomething() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getSomething() {
      Object ref = something_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          something_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSomethingBytes() {
      Object ref = something_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        something_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional .service.example.NestedItem item = 2;
    public static final int ITEM_FIELD_NUMBER = 2;
    private biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItem item_;
    public boolean hasItem() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItem getItem() {
      return item_;
    }
    public biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItemOrBuilder getItemOrBuilder() {
      return item_;
    }
    
    private void initFields() {
      something_ = "";
      item_ = biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItem.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getSomethingBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, item_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getSomethingBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, item_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static biz.neustar.ultra.service.example.ExampleRequestMessage.ExampleRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static biz.neustar.ultra.service.example.ExampleRequestMessage.ExampleRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static biz.neustar.ultra.service.example.ExampleRequestMessage.ExampleRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static biz.neustar.ultra.service.example.ExampleRequestMessage.ExampleRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static biz.neustar.ultra.service.example.ExampleRequestMessage.ExampleRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static biz.neustar.ultra.service.example.ExampleRequestMessage.ExampleRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static biz.neustar.ultra.service.example.ExampleRequestMessage.ExampleRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static biz.neustar.ultra.service.example.ExampleRequestMessage.ExampleRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static biz.neustar.ultra.service.example.ExampleRequestMessage.ExampleRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static biz.neustar.ultra.service.example.ExampleRequestMessage.ExampleRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(biz.neustar.ultra.service.example.ExampleRequestMessage.ExampleRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements biz.neustar.ultra.service.example.ExampleRequestMessage.ExampleRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return biz.neustar.ultra.service.example.ExampleRequestMessage.internal_static_service_example_ExampleRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return biz.neustar.ultra.service.example.ExampleRequestMessage.internal_static_service_example_ExampleRequest_fieldAccessorTable;
      }
      
      // Construct using biz.neustar.ultra.service.example.ExampleRequestMessage.ExampleRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getItemFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        something_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (itemBuilder_ == null) {
          item_ = biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItem.getDefaultInstance();
        } else {
          itemBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return biz.neustar.ultra.service.example.ExampleRequestMessage.ExampleRequest.getDescriptor();
      }
      
      public biz.neustar.ultra.service.example.ExampleRequestMessage.ExampleRequest getDefaultInstanceForType() {
        return biz.neustar.ultra.service.example.ExampleRequestMessage.ExampleRequest.getDefaultInstance();
      }
      
      public biz.neustar.ultra.service.example.ExampleRequestMessage.ExampleRequest build() {
        biz.neustar.ultra.service.example.ExampleRequestMessage.ExampleRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private biz.neustar.ultra.service.example.ExampleRequestMessage.ExampleRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        biz.neustar.ultra.service.example.ExampleRequestMessage.ExampleRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public biz.neustar.ultra.service.example.ExampleRequestMessage.ExampleRequest buildPartial() {
        biz.neustar.ultra.service.example.ExampleRequestMessage.ExampleRequest result = new biz.neustar.ultra.service.example.ExampleRequestMessage.ExampleRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.something_ = something_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (itemBuilder_ == null) {
          result.item_ = item_;
        } else {
          result.item_ = itemBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof biz.neustar.ultra.service.example.ExampleRequestMessage.ExampleRequest) {
          return mergeFrom((biz.neustar.ultra.service.example.ExampleRequestMessage.ExampleRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(biz.neustar.ultra.service.example.ExampleRequestMessage.ExampleRequest other) {
        if (other == biz.neustar.ultra.service.example.ExampleRequestMessage.ExampleRequest.getDefaultInstance()) return this;
        if (other.hasSomething()) {
          setSomething(other.getSomething());
        }
        if (other.hasItem()) {
          mergeItem(other.getItem());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              something_ = input.readBytes();
              break;
            }
            case 18: {
              biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItem.Builder subBuilder = biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItem.newBuilder();
              if (hasItem()) {
                subBuilder.mergeFrom(getItem());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setItem(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string something = 1;
      private Object something_ = "";
      public boolean hasSomething() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getSomething() {
        Object ref = something_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          something_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSomething(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        something_ = value;
        onChanged();
        return this;
      }
      public Builder clearSomething() {
        bitField0_ = (bitField0_ & ~0x00000001);
        something_ = getDefaultInstance().getSomething();
        onChanged();
        return this;
      }
      void setSomething(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        something_ = value;
        onChanged();
      }
      
      // optional .service.example.NestedItem item = 2;
      private biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItem item_ = biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItem.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItem, biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItem.Builder, biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItemOrBuilder> itemBuilder_;
      public boolean hasItem() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItem getItem() {
        if (itemBuilder_ == null) {
          return item_;
        } else {
          return itemBuilder_.getMessage();
        }
      }
      public Builder setItem(biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItem value) {
        if (itemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          item_ = value;
          onChanged();
        } else {
          itemBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setItem(
          biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItem.Builder builderForValue) {
        if (itemBuilder_ == null) {
          item_ = builderForValue.build();
          onChanged();
        } else {
          itemBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeItem(biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItem value) {
        if (itemBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              item_ != biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItem.getDefaultInstance()) {
            item_ =
              biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItem.newBuilder(item_).mergeFrom(value).buildPartial();
          } else {
            item_ = value;
          }
          onChanged();
        } else {
          itemBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearItem() {
        if (itemBuilder_ == null) {
          item_ = biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItem.getDefaultInstance();
          onChanged();
        } else {
          itemBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItem.Builder getItemBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getItemFieldBuilder().getBuilder();
      }
      public biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItemOrBuilder getItemOrBuilder() {
        if (itemBuilder_ != null) {
          return itemBuilder_.getMessageOrBuilder();
        } else {
          return item_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItem, biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItem.Builder, biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItemOrBuilder> 
          getItemFieldBuilder() {
        if (itemBuilder_ == null) {
          itemBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItem, biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItem.Builder, biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItemOrBuilder>(
                  item_,
                  getParentForChildren(),
                  isClean());
          item_ = null;
        }
        return itemBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:service.example.ExampleRequest)
    }
    
    static {
      defaultInstance = new ExampleRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:service.example.ExampleRequest)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_service_example_NestedItem_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_service_example_NestedItem_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_service_example_ExampleRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_service_example_ExampleRequest_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025example_request.proto\022\017service.example" +
      "\"\033\n\nNestedItem\022\r\n\005value\030\001 \001(\t\"N\n\016Example" +
      "Request\022\021\n\tsomething\030\001 \001(\t\022)\n\004item\030\002 \001(\013" +
      "2\033.service.example.NestedItemB:\n!biz.neu" +
      "star.ultra.service.exampleB\025ExampleReque" +
      "stMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_service_example_NestedItem_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_service_example_NestedItem_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_service_example_NestedItem_descriptor,
              new java.lang.String[] { "Value", },
              biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItem.class,
              biz.neustar.ultra.service.example.ExampleRequestMessage.NestedItem.Builder.class);
          internal_static_service_example_ExampleRequest_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_service_example_ExampleRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_service_example_ExampleRequest_descriptor,
              new java.lang.String[] { "Something", "Item", },
              biz.neustar.ultra.service.example.ExampleRequestMessage.ExampleRequest.class,
              biz.neustar.ultra.service.example.ExampleRequestMessage.ExampleRequest.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
