// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example_response.proto

package biz.neustar.ultra.service.example;

public final class ExampleResponseMessage {
  private ExampleResponseMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ExampleResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string item = 2;
    boolean hasItem();
    String getItem();
  }
  public static final class ExampleResponse extends
      com.google.protobuf.GeneratedMessage
      implements ExampleResponseOrBuilder {
    // Use ExampleResponse.newBuilder() to construct.
    private ExampleResponse(Builder builder) {
      super(builder);
    }
    private ExampleResponse(boolean noInit) {}
    
    private static final ExampleResponse defaultInstance;
    public static ExampleResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public ExampleResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return biz.neustar.ultra.service.example.ExampleResponseMessage.internal_static_service_example_ExampleResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return biz.neustar.ultra.service.example.ExampleResponseMessage.internal_static_service_example_ExampleResponse_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string item = 2;
    public static final int ITEM_FIELD_NUMBER = 2;
    private Object item_;
    public boolean hasItem() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getItem() {
      Object ref = item_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          item_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getItemBytes() {
      Object ref = item_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        item_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      item_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(2, getItemBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getItemBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static biz.neustar.ultra.service.example.ExampleResponseMessage.ExampleResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static biz.neustar.ultra.service.example.ExampleResponseMessage.ExampleResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static biz.neustar.ultra.service.example.ExampleResponseMessage.ExampleResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static biz.neustar.ultra.service.example.ExampleResponseMessage.ExampleResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static biz.neustar.ultra.service.example.ExampleResponseMessage.ExampleResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static biz.neustar.ultra.service.example.ExampleResponseMessage.ExampleResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static biz.neustar.ultra.service.example.ExampleResponseMessage.ExampleResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static biz.neustar.ultra.service.example.ExampleResponseMessage.ExampleResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static biz.neustar.ultra.service.example.ExampleResponseMessage.ExampleResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static biz.neustar.ultra.service.example.ExampleResponseMessage.ExampleResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(biz.neustar.ultra.service.example.ExampleResponseMessage.ExampleResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements biz.neustar.ultra.service.example.ExampleResponseMessage.ExampleResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return biz.neustar.ultra.service.example.ExampleResponseMessage.internal_static_service_example_ExampleResponse_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return biz.neustar.ultra.service.example.ExampleResponseMessage.internal_static_service_example_ExampleResponse_fieldAccessorTable;
      }
      
      // Construct using biz.neustar.ultra.service.example.ExampleResponseMessage.ExampleResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        item_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return biz.neustar.ultra.service.example.ExampleResponseMessage.ExampleResponse.getDescriptor();
      }
      
      public biz.neustar.ultra.service.example.ExampleResponseMessage.ExampleResponse getDefaultInstanceForType() {
        return biz.neustar.ultra.service.example.ExampleResponseMessage.ExampleResponse.getDefaultInstance();
      }
      
      public biz.neustar.ultra.service.example.ExampleResponseMessage.ExampleResponse build() {
        biz.neustar.ultra.service.example.ExampleResponseMessage.ExampleResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private biz.neustar.ultra.service.example.ExampleResponseMessage.ExampleResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        biz.neustar.ultra.service.example.ExampleResponseMessage.ExampleResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public biz.neustar.ultra.service.example.ExampleResponseMessage.ExampleResponse buildPartial() {
        biz.neustar.ultra.service.example.ExampleResponseMessage.ExampleResponse result = new biz.neustar.ultra.service.example.ExampleResponseMessage.ExampleResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.item_ = item_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof biz.neustar.ultra.service.example.ExampleResponseMessage.ExampleResponse) {
          return mergeFrom((biz.neustar.ultra.service.example.ExampleResponseMessage.ExampleResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(biz.neustar.ultra.service.example.ExampleResponseMessage.ExampleResponse other) {
        if (other == biz.neustar.ultra.service.example.ExampleResponseMessage.ExampleResponse.getDefaultInstance()) return this;
        if (other.hasItem()) {
          setItem(other.getItem());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000001;
              item_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string item = 2;
      private Object item_ = "";
      public boolean hasItem() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getItem() {
        Object ref = item_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          item_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setItem(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        item_ = value;
        onChanged();
        return this;
      }
      public Builder clearItem() {
        bitField0_ = (bitField0_ & ~0x00000001);
        item_ = getDefaultInstance().getItem();
        onChanged();
        return this;
      }
      void setItem(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        item_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:service.example.ExampleResponse)
    }
    
    static {
      defaultInstance = new ExampleResponse(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:service.example.ExampleResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_service_example_ExampleResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_service_example_ExampleResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026example_response.proto\022\017service.exampl" +
      "e\"\037\n\017ExampleResponse\022\014\n\004item\030\002 \001(\tB;\n!bi" +
      "z.neustar.ultra.service.exampleB\026Example" +
      "ResponseMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_service_example_ExampleResponse_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_service_example_ExampleResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_service_example_ExampleResponse_descriptor,
              new java.lang.String[] { "Item", },
              biz.neustar.ultra.service.example.ExampleResponseMessage.ExampleResponse.class,
              biz.neustar.ultra.service.example.ExampleResponseMessage.ExampleResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
